name: Build and Push Docker Images

on:
  workflow_dispatch:
    inputs:
      version_override:
        description: 'Override version tag'
        required: false
  push:
    paths:
      - 'hacks/auto-backend*'
      - 'atlantis/**'
      - '.devcontainer/**'
      - '.github/workflows/biuld.yaml'

jobs:
  prepare:
    if: ${{ github.event.inputs.version_override == '' }}
    name: Prepare variables
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.prepare.outputs.version }}
    steps:
    - name: Prepare variables
      id: prepare
      shell: bash
      run: |
        BRANCH=$(echo ${GITHUB_REF#refs/heads/})
        COMMIT_SHA_SHORT=$(echo ${GITHUB_SHA} | cut -c1-7)
        echo "::set-output name=version::$(echo ${BRANCH}-${COMMIT_SHA_SHORT})"

  build:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dockerfile: ['atlantis', 'devcontainer']
    env:
      DOCKER_REPO: ghcr.io/${{ github.repository }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64,arm

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: |
          image=moby/buildkit:v0.10.6

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ${{ env.DOCKER_REPO }}/${{ matrix.dockerfile }}
        tags: |
          type=raw,event=push,value=${{github.event.inputs.version_override}},enable=${{github.event.inputs.version_override != ''}},suffix=
          type=raw,event=push,value=latest,enable=${{github.event.inputs.version_override != ''}},suffix=
          type=raw,event=push,value=${{needs.prepare.outputs.version}},enable=${{github.event.inputs.version_override == ''}},suffix=
        flavor: |
          latest=false

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ secrets.GH_CR_USERNAME }}
        password: ${{ secrets.GH_CR_TOKEN }}

    - name: Build and push Docker image
      if: ${{ github.event.inputs.version_override == '' }}
      uses: docker/build-push-action@v5
      with:
        context: ./${{ matrix.dockerfile }}
        platforms: linux/amd64,linux/arm64
        file: ./${{ matrix.dockerfile }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
